# Generated by Django 5.2.3 on 2025-06-21 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=256)),
                ('card_desc', models.CharField(max_length=256)),
                ('card_git_link', models.URLField(max_length=512, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('card_tags', models.JSONField(default=[str])),
                ('card_img_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
