# Generated by Django 5.2.3 on 2025-08-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
