# Generated by Django 5.1.4 on 2025-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=256)),
                ('card_desc', models.CharField(max_length=256)),
                ('card_git_link', models.CharField(max_length=256)),
            ],
        ),
    ]
